default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  enconding: unicode
  database: dbrhei0plt6ttm
  pool: 5
  username: stzzjlvhlbzzsz
