# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce95d071478750aee8eb5af8de79349c66787c30892c88dceee1c01aef3d8e215c1491ca0f86da056e2c567ad94a44ebf8b4c913708c48c8426606965bedfade

test:
  secret_key_base: 7c0e5b6005e1371ad28b2bcda08c2e4d7cc51f0d0acbdb2b0ebd246db426a396a9c26b2af94c1eb724a271f377b256249ffa177eb2256de3b8ee8b2f3bd82c32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7ab1d0f174711b2a256a9251cc1beee2a90cae38bf6b994d6968b4f429163b66c63ccf9ced58b20d55a8656a11effdf41d9272a83613b5dbf708ac3a3cc847b3